[terminal.shell]
program = "C:\\Windows\\System32\\wsl.exe"
args = ["-d Debian", "--cd ~"]

[window]
padding = { x = 5, y = 5 }
dynamic_padding = true
decorations = "None"

[font]
normal = { family = "FiraCode Nerd Font", style = "Medium" }
bold = { family = "FiraCode Nerd Font", style = "SemiBold" }
size = 11.5

[mouse]
hide_when_typing = true

[selection]
save_to_clipboard = true

[[keyboard.bindings]]
key = "Space"
mods = "Control"
chars = "\u0000"

[colors.primary]
background = "#273136"
foreground = "#F2FFFC"

[colors.cursor]
text = "#273136"   # Background color to invert for cursor
cursor = "#F2FFFC" # Cursor color

[colors.selection]
text = "#273136"       # Inverted for selection
background = "#6B7678"

[colors.normal]
black = "#1D2528"
red = "#FF6D7E"
green = "#A2E57B"
yellow = "#FFED72"
blue = "#FFB270"
magenta = "#BAA0F8"
cyan = "#7CD5F1"
white = "#B8C4C3"

[colors.bright]
black = "#545F62"
red = "#FF6D7E"
green = "#A2E57B"
yellow = "#FFED72"
blue = "#FFB270"
magenta = "#BAA0F8"
cyan = "#7CD5F1"
white = "#F2FFFC"
